### ISSUE TITLE
rename to python-magento-xmlrpc maybe?

### ISSUE THREAD

**Issue by nyov** [bernieke/python-magento#1]
To distinguish from soap and rest api clients (or other magento interfacing py software), it might make sense to add '-xmlrpc' while you're at it.
Sadly magento2 won't have an xmlrpc api any longer it seems.

**Comment by bernieke** [comment]
Personally I don't even consider soap or rest to be a valid alternative to xmlrpc for the magento(1) api. (See http://www.bluehut.net/blog/2012/calling-magento-api-from-python.html)

So I'd actually propose naming any soap (or rest, in case it finally has equivalent features) client aimed at magento2 python-magento2...

**Comment by nyov** [comment]
I agree, a rest-request for every operation (product import or so) is relatively slow and soap is not my thing. (I prefer the magmi-like approach of going directly to database, where possible. Or not using magento at all.)
But that's not really my point here. I also would prefer anything api-related for magento2 to be called something `-magento2-api`-something like. `python-magento` is so very generic it could be anything from a magento product management tool, to a database importer to a php bridge.

But then most similar projects aren't [any more distinctive](https://github.com/search?q=python+magento) in their naming either.
Now that I made my case, please feel free to close the issue either way.
