### ISSUE TITLE
set the customer addresses in the shopping cart

### ISSUE THREAD

**Issue by euroblaze** [bernieke/python-magento#13]
I am trying to create an order. The steps to create a quote and set a customer work well, but I cannot set customer addresses. I have send the params as suggested in http://devdocs.magento.com/guides/m1x/api/soap/checkout/cartCustomer/cart_customer.addresses.html and below is error stack

Traceback (most recent call last):  
  File "D:\mage_connect\mage_connect\mageapp\addons\magento_bridge\models\mob_synchronization.py", line 1168, in _export_specific_order
    mage_resultCustomerAddresses = magento.cart_customer.addresses(mage_shoppingCartId, customer_address_data)
  File "C:\Program Files\Anaconda2\lib\site-packages\magento\magento_api.py", line 206, in call_method
    return self._client.call(self._session_id, path, args)
  File "C:\Program Files\Anaconda2\lib\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files\Anaconda2\lib\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Program Files\Anaconda2\lib\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Program Files\Anaconda2\lib\xmlrpclib.py", line 1331, in single_request
    response.msg,
ProtocolError: <ProtocolError for magento-odoo.mage_connect.com:80/api/xmlrpc: 500 Internal Server Error>

and 
`customer_address_data = [
	{
		'city': u'test',
		'fax': u'',
		'telephone ': u'', 
		'firstname': u'patrik',
		'lastname': u'test',
		'region': False,
		'country_id': u'DE', 
		'is_default_shipping': 0, 
		'street': u'test',
		'is_default_billing': 1,
		'postcode': u'43332', 
		'email': u'patrik@gmx.de',
		'mode': 'billing'
	}, 
	{
		'city': u'test', 
		'fax': False, 
		'telephone ': False, 
		'firstname': u'patrik', 
		'lastname': u'test', 
		'region': False, 
		'country_id': u'DE', 
		'is_default_shipping': 1, 
		'street': u'test', 
		'is_default_billing': 0, 
		'postcode': u'43332', 
		'email': u'patrik@gmx.de', 
		'mode': 'shipping'
	}
]`

any hints of how to resolve the issue?
Thanks in advance

**Comment by Bobspadger** [comment]
It looks like you are getting an error from the server, not from the python code.

```
ProtocolError: <ProtocolError for magento-odoo.mage_connect.com:80/api/xmlrpc: 500 Internal Server Error>
```

Which is a protocol error, have you checked if you are using `http/https` and that you are running on the correct ports?
