### ISSUE TITLE
Version 1.0.0 missing from PyPI simple index

### ISSUE THREAD

**Issue by sunahfloship** [bernieke/python-magento#5]
I was previously installing python-magento from this repo since PyPI didn't have the official release yet, but I saw the official PyPI page showed the current version as 1.0.0, so I tried installing it from PyPI with pip. The latest version that pip could find, though, was 0.3.3 -- I did a little debugging and it looks like the package's simple index hasn't been updated with the distribution for 1.0.0:
https://pypi.python.org/simple/python-magento/

Some not-very-extensive Googling seems to suggest that a project maintainer needs to upload a distribution for 1.0.0 either from a web form or via the setup.py script: https://docs.python.org/3.4/distutils/packageindex.html#package-index

**Comment by bernieke** [comment]
Oops :)

I just did the upload thing, and I can see the tar ball there now, so hopefully everything is ok now.

**Comment by sunahfloship** [comment]
Added the pip version to our requirements file and it worked. Thanks!
