### ISSUE TITLE
magento.cataloginventory_stock_item.update - Product not exists.

### ISSUE THREAD

**Issue by maltitco** [bernieke/python-magento#9]
Hello, I have a problem with updating the quantity of products at the SKU.

in IPython:
`magento.cataloginventory_stock_item.update({'sku': 'OTTest'}, {'qty': '332'})`
gives me:
`Fault: <Fault 101: 'Product not exists.'>`

but

```
In [107]: magento.cataloginventory_stock_item.update({'product_id': '8372'}, {'qty': '332'})
Out[107]: True
```

OTTest id=8372

What is the reason that you can not update the amount of the "SKU"

**Comment by bernieke** [comment]
Couldn't tell you.

python-magento just wraps the xml-rpc interface, so if you manage to get it working directly through xml-rpc, it should work through python-magento as well...

**Comment by maltitco** [comment]
The problem was on the side of magento.
